export const SERVER_URL = "http://192.168.11.10:8080"
export const REGISTER = "/api/auth/register"
export const LOGIN = "/api/auth/login"
export const ACCOUNT_DATA = "/api/auth/account-data"
export const CREATE_ORDER = "/api/orders/create-order"
export const ORGANIZATION_ORDERS = "/api/organization/orders"
export const BARREL_COMPONENTS = "/api/barrel/components"