export const SERVER_URL = "http://192.168.146.145:8080"
export const REGISTER = "/api/auth/register"
export const LOGIN = "/api/auth/login"
export const ACCOUNT_DATA = "/api/auth/account-data"
export const CREATE_ORDER = "/api/order/create-order"
export const ORDERS_BY_ACCOUNT = "/api/order/orders-by-account"
export const BARREL_COMPONENTS = "/api/barrel/components"