export const STATUSES = {
    IDLE: "IDLE",
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
    ORDER_STATUS_ERROR: "ORDER_STATUS_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    LOADING: "LOADING"
}

export const ORDER_STATUSES = {
    CREATED: 'CREATED',
    PICKED: 'PICKED',
    TAKEN: 'TAKEN',
    INSPECTION: 'INSPECTION',
    READY: 'READY',
    COMING: 'COMING',
    COMPLETED: 'COMPLETED'
}