export const STATUSES = {
    IDLE: "IDLE",
    SUCCESS: "SUCCESS",
    ERROR: "ERROR"
}

export const ORDER_STATUSES = {
    CREATED: 'CREATED',
    PICKED: 'PICKED',
    TAKEN: 'TAKEN',
    INSPECTION: 'INSPECTION',
    READY: 'READY',
    COMING: 'COMING',
    COMPLETED: 'COMPLETED'
}